plugins {
    id 'com.android.application'
}
android {
    namespace 'com.lsp.sidebar.scene'
    compileSdk 35
    defaultConfig {
        applicationId "com.lsp.sidebar.scene"
        minSdk 28
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
dependencies {
    // Xposed API 82（经典 API，LSPosed 完全兼容；运行时由框架提供，所以用 compileOnly）
    compileOnly 'de.robv.android.xposed:api:82'
}
